### ISSUE TITLE
Group of issues found during tests of next release candidate

### ISSUE THREAD

**Issue by benerken** [rero/rero-ils-ui#108]
This issue is composed of all reviews for the next release candidate of RERO-ils + RERO-ils-ui.

It first starts with specific branch (check next paragraph), then it continues on **dev** branchs of **rero-ils** and **rero-ils-ui** (after v0.5.2).

**Software version**
RERO ILS: dev branch, commit https://github.com/rero/rero-ils/commit/53269cc18d05f01e77d6e716ba479d694716b080

Tested on https://ilsdev.test.rero.ch with login reroilstest+jean@gmail.com (Librarian Org1)

### Blocking issues
- [x] 5. logos are pixelated: insert svg pics (example: public view of ils.test.rero.ch) or higher quality pics -> doo [SOLVED]

### Important issues
- [x] 1. Count of person tab for organisation is not correct (Global is correct). -> zub [SOLVED] https://github.com/rero/rero-ils-ui/pull/139
- [x] 2. Autocomplete: you type a search in the box but you must click in the box to see the result of autocomplete (maybe related to 4.)-> zaa: not related to 4., created an issue: https://github.com/rero/rero-ils/issues/788
- [x] 3. Autocomplete doesn't work if your search contains diactrictics (try: réalité and realite) -> zaa: created an issue : https://github.com/rero/rero-ils-ui/issues/186
- [x] 4. [mii: see issue [145](https://github.com/rero/rero-ils-ui/issues/145)] Autocomplete slow
Autocomplete: https://tree.taiga.io/project/rero21-reroils/task/1294?kanban-status=1224894 -> baa, zub [IN PROGRESS] 

### Low priority issues
- [x] 4. A document without holding/item shouldn't be displayed in global public view, but only in professional view. [SOLVED]: It's a normal situation (zub)
- [x] 25. Dropdown menus on the right could have `.dropdown-menu-right` bootstrap class, to avoid that the menu is outside of the window. Also on the professional interface. [SOLVED] -> zub: https://github.com/rero/ng-core/pull/130 and https://github.com/rero/rero-ils-ui/pull/134

### Blocking issues
- [x] 1. Documents : display of the form is delayed (5 seconds) with Firefox. No problem with Chrome and Safari [fixed by ngx-formly]
- [x] 2. Document View : An author linked to a MEF references not displayed in the document detail screen, in the professional view. But he's correctly displayed in the public view. [SOLVED: 2019-01-30]
- [x] 3. Documents : Import EAN 9782220063201. You can't save the document. You get an error 400 "Bad Request". "Validation error: ["Agir à gauche, l'économie sociale et solidaire", "suivi de Propositions pour une politique en faveur de l'économie sociale et solidaire"] is not of type 'string'. [not related to the editor, a separate issue can be open] -> wep: [SOLVED] with https://github.com/rero/rero-ils/pull/733
- [x] 6. Holdings/Items: Try to add a new holding/Item to a document. When you save, you get an error 400 "Bad Request". Validation error: 'status' is a required property." [Issue linked to n°16, solved for a workshop but the status needs to be hidden in editor] -> zaa: solved with https://github.com/rero/rero-ils/pull/728
- [x] 15. Editor: [mii: will be done through transifex, mainly.]
   - [x] translation issue in the types of "Identifiers" (see below). There is a "mess". 
   - [x] contents of various drop menus are a "mess". Examples: country, canton 
   - [x] some field labels are replaced by language names (aléoute, lushaï). See field provisionActivity.
   
![image](https://user-images.githubusercontent.com/16501502/73357888-b445e680-429d-11ea-8aa9-68bf4ccab1d1.png)
- [x] 16. Editor: The item types are not filtered in the item editor. So, if you select an item types not belonging to your institution, you can't save the item. [Issue linked to n°6.]
- [x] 18. Search: In the professional view, there is no tabs "Documents" and "Persons" like in the public view. Why?: because those views are separated in professional view (Catalog -> Documents and Catalog -> Persons)
- [x] 19. Editor: the label of Provision activity button is too long [translation of provision activity in Transifex [mii proposal: add `.overflow-hidden` class to the button inside the list element]. -> zub [SOLVED] https://github.com/rero/ng-core/pull/131
![image](https://user-images.githubusercontent.com/16501502/73430232-d3945080-433d-11ea-9673-3ee2b72fd90c.png)
- [x] 23. Import in the document editor, some of the following problems appear (not stable, same behaviour not always reproducible). It may be linked to fields *provisionActivity* and *editionStatement*
   - [x] when I import some documents (9782261403417), I cannot save them. -> wep: [SOLVED] with rero/rero-ils#733
   - [x] when I import some documents (9782072862014, 9782754035712, 9782754712279), the field provisionActivity is not displayed for edition. -> wep: [SOLVED] with rero/rero-ils#733
   - [x] when I import some document and save (9782072862014), the field provisionActivity is displayed twice in the detailed view (public and admin). wep -> tags 210 and 214 present for this notice!

- [x] 26. Item Editor: The locations are not filtered. The user "Jean" can see all locations of all libraries of its institution (see https://github.com/rero/rero-ils/issues/697). -> zub: [SOLVED] https://github.com/rero/rero-ils-ui/pull/129
- [x] 29. Item editor: edit a holding item. This raises an HTTP 400 error: "Validation error: Additional properties are not allowed ('available' was unexpected)." -> zub: [SOLVED] https://github.com/rero/rero-ils-ui/pull/137

### Important issues

- [x] 7. Results page: the facet "libraries" is missing in the professional View. It exists in the public view.   [not related to the editor] : created an issue https://github.com/rero/rero-ils-ui/issues/140
- [x] 8. Search: Both in public and professional view, when you look for an author, the autocomplete function doesn't display results about Person.  Only about documents for now. (Ex. : Olmi, Véronique) [SOLVED: 2019-01-30]
- [x] 11. Search input does not take all the width in the header in the public view. -> doo : solved with https://github.com/rero/rero-ils/pull/724
- [x] 12. Too much menus for system librarian in the admin view. -> zaa : needs to be discussed, created a storyless task (https://tree.taiga.io/project/rero21-reroils/task/1291?kanban-status=1224893)
- [x] 13. Facets are not the same between global and organisation views; the authors is not always open. [SOLVED: 2019-01-30]
- [x] 17. Persons: In the professional view, in the person detail page, there is no link to the documents. -> zub: https://github.com/rero/rero-ils-ui/pull/126
- [x] 21. The options of the select menu is not sorted alphabetically. -> zub [SOLVED] https://github.com/rero/rero-ils/pull/731
- [x] 22. Replace text "RERO ILS" by the logo in admin view (as before) -> zub [SOLVED] https://github.com/rero/rero-ils-ui/pull/138
- [x] 24. In the document editor, it is impossible to add subfield "source" to field "identifier" -> maj: fixed https://github.com/rero/rero-ils/pull/746
- [x] 25. In the document editor, it is possible to delete date subfield (inside statement inside provisionActivity). The save button is then activated, but doesn't work. Trying to cancel, the document cannot be displayed anymore (server error). -> maj: fixed https://github.com/rero/rero-ils/pull/746
- [x] 37. It is possible to delete an acquisition account, even if order lines are linked to it. It should be impossible. -> baa: fixed in https://github.com/rero/rero-ils/pull/737
- [x] when I import some documents (9782297066563), various fields with values are not displayed in the editor (notes, provisionActivity, editionStatement, ...)

### Low priority issues
- [x] 4. Documents: when you add a new document, it doesn't check if it already exists (ex. check ISBN) to avoid duplicates. [more a US than an issue, closed]
- [x] 20. Document Import EAN 9782035930910 doesn't work: Message in browser console: ERROR TypeError: "You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable." -> wep: [SOLVED] with https://github.com/rero/rero-ils/pull/733
- [x] 5. Documents: In the editor, you need to click twice on the left buttons (shortcuts) to add Notes, Subjects, Proper Titles in the document form. [This is a normal behaviour one to exit the input field one to click the button, need to find a solution]-> https://github.com/rero/ng-core/pull/135

- [x] 32. A librarian can change his/her affiliation library in the editor (should not be possible). After this change, "My library" still displays the first affiliation library. -> zub: Create a simple issue with this case. [zaa: created https://github.com/rero/rero-ils-ui/issues/185]
- [x] 36. In the document editor, the field "abstract" should be bigger or be expanded when text is entered. --> zan SOLVED : https://github.com/rero/rero-ils/pull/754

### Blocking issues
- [x] 9. During a checkout, item appears twice. Take Patron Broglio, Giulia (2050124312) with Item barcode 10000000784 [addressed during the circulation-ui US]. -> zaa : solved with https://github.com/rero/rero-ils-ui/pull/119
- [x] 10. Checkin doesn't work after merge in US813-circulation-ui https://github.com/rero/rero-ils-ui/commit/9db2f91c101eb0e765cb841e5785b5a21a04c696 -> zaa : solved with https://github.com/rero/rero-ils-ui/pull/121
- [x] 33. Item in transit back to home library: it should become "on shelf". Error in Circ UI, see image below: it should display target transit library. -> zaa + jma: https://github.com/rero/rero-ils/pull/749 & https://github.com/rero/rero-ils-ui/pull/152
![image](https://user-images.githubusercontent.com/8154915/73672174-b5678100-46ac-11ea-8b7a-8be979b21db4.png)
- [x] 35. 10000000064 and 10000000087: no details displayed, "ERROR TypeError: Cannot read property 'pickup_location_pid' of undefined" in console -> zaa: https://github.com/rero/rero-ils-ui/pull/131

### Important issues
- [x] 15. A checkout done on an item that is already on loan is blocked, but the flash message is displayed twice [addressed during the circulation-ui US]. -> zaa: https://github.com/rero/rero-ils-ui/pull/131
- [x] 27. On loan view, the link on barcode redirects to the loan page instead of patron profile. -> zaa solved with: https://github.com/rero/rero-ils-ui/pull/128
- [x] 28. Focus is not set to search input in Circulation view -> zaa: solved with https://github.com/rero/rero-ils-ui/pull/132
- [x] 30. Error "Une erreur est survenue sur le serveur : error: unsupported type for timedelta days component: NoneType".
   - Ex. 1: when there is no circulation policy defined for a patron_type + item_type; do a checkout with John,Smith 2000000001 (patron type : children) with barcode 10000000087 or 10000000064. -> zaa: https://github.com/rero/rero-ils-ui/pull/131
- [x] 31. Trying to do a checkout for patron A of an item already on loan by patron B. It should be blocked. Result: it does a checkin.-> zaa: https://github.com/rero/rero-ils-ui/pull/131
- [x] 34. It's possible to do a checkout on an item for patron A when the item is requested for patron B [zaa: according to daily discussion, needs to be checked by PO with the particular case] -> zaa: https://github.com/rero/rero-ils-ui/pull/131
